# app.py
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate_code():
    try:
        data = request.get_json()
        user_message = data.get('message', '').lower()
        
        if not user_message:
            return jsonify({'error': 'No message provided'}), 400
        
        response = generate_response(user_message)
        
        return jsonify({
            'response': response,
            'status': 'success'
        })
        
    except Exception as e:
        return jsonify({
            'error': str(e),
            'status': 'error'
        }), 500

def generate_response(message):
    """Generate code responses based on keywords in the message"""
    
    # Login Form
    if any(word in message for word in ['login', 'form', 'signin', 'sign-in']):
        return (
            "Here's a responsive login form with HTML and CSS:\n\n"
            "```html\n"
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "<head>\n"
            "    <meta charset=\"UTF-8\">\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "    <title>Responsive Login Form</title>\n"
            "    <style>\n"
            "        * {\n"
            "            margin: 0;\n"
            "            padding: 0;\n"
            "            box-sizing: border-box;\n"
            "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
            "        }\n"
            "        \n"
            "        body {\n"
            "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
            "            height: 100vh;\n"
            "            display: flex;\n"
            "            justify-content: center;\n"
            "            align-items: center;\n"
            "            padding: 20px;\n"
            "        }\n"
            "        \n"
            "        .login-container {\n"
            "            background: white;\n"
            "            padding: 40px;\n"
            "            border-radius: 10px;\n"
            "            box-shadow: 0 15px 35px rgba(0,0,0,0.2);\n"
            "            width: 100%;\n"
            "            max-width: 400px;\n"
            "        }\n"
            "        \n"
            "        h2 {\n"
            "            text-align: center;\n"
            "            color: #333;\n"
            "            margin-bottom: 30px;\n"
            "            font-size: 28px;\n"
            "        }\n"
            "        \n"
            "        .input-group {\n"
            "            margin-bottom: 20px;\n"
            "        }\n"
            "        \n"
            "        label {\n"
            "            display: block;\n"
            "            margin-bottom: 5px;\n"
            "            color: #555;\n"
            "            font-weight: 500;\n"
            "        }\n"
            "        \n"
            "        input {\n"
            "            width: 100%;\n"
            "            padding: 12px;\n"
            "            border: 2px solid #e0e0e0;\n"
            "            border-radius: 5px;\n"
            "            font-size: 16px;\n"
            "            transition: border-color 0.3s;\n"
            "        }\n"
            "        \n"
            "        input:focus {\n"
            "            outline: none;\n"
            "            border-color: #667eea;\n"
            "        }\n"
            "        \n"
            "        button {\n"
            "            width: 100%;\n"
            "            padding: 12px;\n"
            "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
            "            color: white;\n"
            "            border: none;\n"
            "            border-radius: 5px;\n"
            "            font-size: 16px;\n"
            "            font-weight: 600;\n"
            "            cursor: pointer;\n"
            "            transition: transform 0.2s;\n"
            "        }\n"
            "        \n"
            "        button:hover {\n"
            "            transform: translateY(-2px);\n"
            "        }\n"
            "        \n"
            "        .links {\n"
            "            margin-top: 20px;\n"
            "            text-align: center;\n"
            "            display: flex;\n"
            "            justify-content: space-between;\n"
            "        }\n"
            "        \n"
            "        .links a {\n"
            "            color: #667eea;\n"
            "            text-decoration: none;\n"
            "            font-size: 14px;\n"
            "        }\n"
            "        \n"
            "        .links a:hover {\n"
            "            text-decoration: underline;\n"
            "        }\n"
            "        \n"
            "        @media (max-width: 480px) {\n"
            "            .login-container {\n"
            "                padding: 30px 20px;\n"
            "            }\n"
            "            \n"
            "            .links {\n"
            "                flex-direction: column;\n"
            "                gap: 10px;\n"
            "            }\n"
            "        }\n"
            "    </style>\n"
            "</head>\n"
            "<body>\n"
            "    <div class=\"login-container\">\n"
            "        <h2>Welcome Back</h2>\n"
            "        <form>\n"
            "            <div class=\"input-group\">\n"
            "                <label for=\"email\">Email</label>\n"
            "                <input type=\"email\" id=\"email\" placeholder=\"Enter your email\" required>\n"
            "            </div>\n"
            "            <div class=\"input-group\">\n"
            "                <label for=\"password\">Password</label>\n"
            "                <input type=\"password\" id=\"password\" placeholder=\"Enter your password\" required>\n"
            "            </div>\n"
            "            <button type=\"submit\">Login</button>\n"
            "            <div class=\"links\">\n"
            "                <a href=\"#\">Forgot Password?</a>\n"
            "                <a href=\"#\">Create Account</a>\n"
            "            </div>\n"
            "        </form>\n"
            "    </div>\n"
            "</body>\n"
            "</html>\n"
            "```\n\n"
            "This login form features:\n"
            "✅ Responsive design\n"
            "✅ Modern gradient background\n"
            "✅ Smooth hover effects\n"
            "✅ Input focus animations\n"
            "✅ Mobile-friendly layout"
        )
    
    # Navigation Bar
    elif any(word in message for word in ['navbar', 'navigation', 'menu', 'dropdown']):
        return (
            "Here's a responsive navigation bar with dropdown menu:\n\n"
            "```html\n"
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "<head>\n"
            "    <meta charset=\"UTF-8\">\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "    <title>Responsive Navbar</title>\n"
            "    <style>\n"
            "        * {\n"
            "            margin: 0;\n"
            "            padding: 0;\n"
            "            box-sizing: border-box;\n"
            "            font-family: Arial, sans-serif;\n"
            "        }\n"
            "        \n"
            "        nav {\n"
            "            background: #333;\n"
            "            padding: 1rem;\n"
            "        }\n"
            "        \n"
            "        .nav-container {\n"
            "            max-width: 1200px;\n"
            "            margin: 0 auto;\n"
            "            display: flex;\n"
            "            justify-content: space-between;\n"
            "            align-items: center;\n"
            "        }\n"
            "        \n"
            "        .logo a {\n"
            "            color: white;\n"
            "            font-size: 24px;\n"
            "            text-decoration: none;\n"
            "        }\n"
            "        \n"
            "        .nav-menu {\n"
            "            display: flex;\n"
            "            list-style: none;\n"
            "            gap: 20px;\n"
            "        }\n"
            "        \n"
            "        .nav-menu a {\n"
            "            color: white;\n"
            "            text-decoration: none;\n"
            "            padding: 10px;\n"
            "        }\n"
            "        \n"
            "        .dropdown-content {\n"
            "            display: none;\n"
            "            position: absolute;\n"
            "            background: white;\n"
            "            min-width: 160px;\n"
            "            box-shadow: 0 8px 16px rgba(0,0,0,0.2);\n"
            "        }\n"
            "        \n"
            "        .dropdown:hover .dropdown-content {\n"
            "            display: block;\n"
            "        }\n"
            "        \n"
            "        .dropdown-content a {\n"
            "            color: #333;\n"
            "            padding: 12px 16px;\n"
            "            display: block;\n"
            "        }\n"
            "        \n"
            "        .menu-toggle {\n"
            "            display: none;\n"
            "            color: white;\n"
            "            font-size: 24px;\n"
            "            cursor: pointer;\n"
            "        }\n"
            "        \n"
            "        @media (max-width: 768px) {\n"
            "            .menu-toggle {\n"
            "                display: block;\n"
            "            }\n"
            "            \n"
            "            .nav-menu {\n"
            "                display: none;\n"
            "                position: absolute;\n"
            "                top: 70px;\n"
            "                left: 0;\n"
            "                right: 0;\n"
            "                background: #333;\n"
            "                flex-direction: column;\n"
            "                padding: 20px;\n"
            "            }\n"
            "            \n"
            "            .nav-menu.active {\n"
            "                display: flex;\n"
            "            }\n"
            "        }\n"
            "    </style>\n"
            "</head>\n"
            "<body>\n"
            "    <nav>\n"
            "        <div class=\"nav-container\">\n"
            "            <div class=\"logo\">\n"
            "                <a href=\"#\">Logo</a>\n"
            "            </div>\n"
            "            <div class=\"menu-toggle\">☰</div>\n"
            "            <ul class=\"nav-menu\">\n"
            "                <li><a href=\"#\">Home</a></li>\n"
            "                <li><a href=\"#\">About</a></li>\n"
            "                <li class=\"dropdown\">\n"
            "                    <a href=\"#\">Services</a>\n"
            "                    <div class=\"dropdown-content\">\n"
            "                        <a href=\"#\">Web Design</a>\n"
            "                        <a href=\"#\">Development</a>\n"
            "                        <a href=\"#\">SEO</a>\n"
            "                    </div>\n"
            "                </li>\n"
            "                <li><a href=\"#\">Contact</a></li>\n"
            "            </ul>\n"
            "        </div>\n"
            "    </nav>\n"
            "    <script>\n"
            "        document.querySelector('.menu-toggle').addEventListener('click', function() {\n"
            "            document.querySelector('.nav-menu').classList.toggle('active');\n"
            "        });\n"
            "    </script>\n"
            "</body>\n"
            "</html>\n"
            "```\n\n"
            "Features:\n"
            "✅ Responsive mobile menu\n"
            "✅ Dropdown functionality\n"
            "✅ Clean design\n"
            "✅ Hamburger menu on mobile"
        )
    
    # Python Function
    elif any(word in message for word in ['python', 'function', 'prime']):
        return (
            "Here's a Python function to check prime numbers:\n\n"
            "```python\n"
            "def is_prime(n):\n"
            "    '''\n"
            "    Check if a number is prime.\n"
            "    \n"
            "    Args:\n"
            "        n (int): Number to check\n"
            "        \n"
            "    Returns:\n"
            "        bool: True if prime, False otherwise\n"
            "    '''\n"
            "    if n <= 1:\n"
            "        return False\n"
            "    if n <= 3:\n"
            "        return True\n"
            "    if n % 2 == 0 or n % 3 == 0:\n"
            "        return False\n"
            "    \n"
            "    i = 5\n"
            "    while i * i <= n:\n"
            "        if n % i == 0 or n % (i + 2) == 0:\n"
            "            return False\n"
            "        i += 6\n"
            "    \n"
            "    return True\n"
            "\n"
            "# Test the function\n"
            "numbers = [2, 3, 4, 5, 17, 19, 20, 23, 29, 30]\n"
            "for num in numbers:\n"
            "    if is_prime(num):\n"
            "        print(f'{num} is prime')\n"
            "    else:\n"
            "        print(f'{num} is not prime')\n"
            "```\n\n"
            "Features:\n"
            "✅ Efficient algorithm\n"
            "✅ Handles edge cases\n"
            "✅ Easy to use"
        )
    
    # JavaScript Calculator
    elif any(word in message for word in ['javascript', 'js', 'calculator']):
        return (
            "Here's a simple calculator in JavaScript:\n\n"
            "```javascript\n"
            "class Calculator {\n"
            "    constructor() {\n"
            "        this.result = 0;\n"
            "    }\n"
            "    \n"
            "    add(a, b) {\n"
            "        this.result = a + b;\n"
            "        return this.result;\n"
            "    }\n"
            "    \n"
            "    subtract(a, b) {\n"
            "        this.result = a - b;\n"
            "        return this.result;\n"
            "    }\n"
            "    \n"
            "    multiply(a, b) {\n"
            "        this.result = a * b;\n"
            "        return this.result;\n"
            "    }\n"
            "    \n"
            "    divide(a, b) {\n"
            "        if (b === 0) {\n"
            "            throw new Error('Cannot divide by zero');\n"
            "        }\n"
            "        this.result = a / b;\n"
            "        return this.result;\n"
            "    }\n"
            "    \n"
            "    clear() {\n"
            "        this.result = 0;\n"
            "    }\n"
            "}\n"
            "\n"
            "// Usage example\n"
            "const calc = new Calculator();\n"
            "console.log(calc.add(5, 3));      // 8\n"
            "console.log(calc.subtract(10, 4)); // 6\n"
            "console.log(calc.multiply(3, 7));  // 21\n"
            "console.log(calc.divide(15, 3));   // 5\n"
            "```\n\n"
            "Features:\n"
            "✅ Class-based design\n"
            "✅ Error handling\n"
            "✅ Basic operations"
        )
    
    # Default response
    else:
        return (
            "I can help you generate various types of code! Here are some examples:\n\n"
            "🌐 **Web Development**\n"
            "- 'Create a login form with HTML and CSS'\n"
            "- 'Generate a navigation bar with dropdown'\n"
            "- 'Make a responsive product card'\n\n"
            "💻 **JavaScript**\n"
            "- 'Create a calculator in JavaScript'\n"
            "- 'Make a countdown timer'\n"
            "- 'Generate a to-do list app'\n\n"
            "🐍 **Python**\n"
            "- 'Create a prime number function'\n"
            "- 'Generate a weather API integration'\n"
            "- 'Make a file organizer script'\n\n"
            "📊 **Database**\n"
            "- 'Create SQL queries for users'\n"
            "- 'Generate MongoDB schema'\n\n"
            "**Try one of these examples!** Just type your request and I'll generate the code for you."
        )

if __name__ == '__main__':
    app.run(debug=True, port=5000)